apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}-collectd
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  collectd.conf: |
    LoadPlugin "varnish"
    <Plugin "varnish">
        <Instance "varnishd">
            CollectBackend     {{ if .Values.collectdVarnish.CollectBackend }}true{{ else }}false{{ end }}
            CollectBan         {{ if .Values.collectdVarnish.CollectBan }}true{{ else }}false{{ end }}
            CollectCache       {{ if .Values.collectdVarnish.CollectCache }}true{{ else }}false{{ end }}
            CollectConnections {{ if .Values.collectdVarnish.CollectConnections }}true{{ else }}false{{ end }}
            CollectESI         {{ if .Values.collectdVarnish.CollectESI }}true{{ else }}false{{ end }}
            CollectFetch       {{ if .Values.collectdVarnish.CollectFetch }}true{{ else }}false{{ end }}
            CollectHCB         {{ if .Values.collectdVarnish.CollectHCB }}true{{ else }}false{{ end }}
            CollectObjects     {{ if .Values.collectdVarnish.CollectObjects }}true{{ else }}false{{ end }}
            CollectSession     {{ if .Values.collectdVarnish.CollectSession }}true{{ else }}false{{ end }}
            CollectSHM         {{ if .Values.collectdVarnish.CollectSHM }}true{{ else }}false{{ end }}
            CollectSMS         {{ if .Values.collectdVarnish.CollectSMS }}true{{ else }}false{{ end }}
            CollectStruct      {{ if .Values.collectdVarnish.CollectStruct }}true{{ else }}false{{ end }}
            CollectTotals      {{ if .Values.collectdVarnish.CollectTotals }}true{{ else }}false{{ end }}
            CollectUptime      {{ if .Values.collectdVarnish.CollectUptime }}true{{ else }}false{{ end }}
            CollectVCL         {{ if .Values.collectdVarnish.CollectVCL }}true{{ else }}false{{ end }}
            CollectVSM         {{ if .Values.collectdVarnish.CollectVSM }}true{{ else }}false{{ end }}
            CollectWorkers     {{ if .Values.collectdVarnish.CollectWorkers }}true{{ else }}false{{ end }}
        </Instance>
    </Plugin>
