apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
